--DROP TABLE "DTL_BPM_INST_DIA";

CREATE TABLE "DTL_BPM_INST_DIA" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "INST_DIA_CODE" VARCHAR2(50) DEFAULT ('INS4' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "INST_MASTER_CODE" VARCHAR2(50),
   "STEP_INFO" CLOB,
   "LANE_INFO" CLOB,
	 "CREATE_DATE" DATE DEFAULT SYSDATE,
   CONSTRAINT "DTL_BPM_INST_DIA_PK" PRIMARY KEY ("ID")
   );
   COMMENT ON COLUMN "DTL_BPM_INST_DIA"."INST_DIA_CODE" IS 'Mã quản lý Diagram theo Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_DIA"."INST_MASTER_CODE" IS 'Mã quản lý Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_DIA"."STEP_INFO" IS 'Info data của Step theo Instance';
   COMMENT ON COLUMN "DTL_BPM_INST_DIA"."LANE_INFO" IS 'Info data của Lane theo Instance';
   COMMENT ON COLUMN "DTL_BPM_INST_DIA"."CREATE_DATE" IS 'Ngày tạo trên database. Default = SYSDATE';
