--DROP TABLE "DTL_BPM_INST_TASK";

CREATE TABLE "DTL_BPM_INST_TASK" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "INST_TASK_CODE" VARCHAR2(50) DEFAULT ('INS5' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "INST_MASTER_CODE" VARCHAR2(50),
   "TASK_ID" VARCHAR2(50),
   "DATA" CLOB,
	 "CREATE_DATE" DATE DEFAULT SYSDATE,
   CONSTRAINT "DTL_BPM_INST_TASK_PK" PRIMARY KEY ("ID")
   );
   COMMENT ON COLUMN "DTL_BPM_INST_TASK"."INST_TASK_CODE" IS 'Mã quản lý Task theo Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_TASK"."INST_MASTER_CODE" IS 'Mã quản lý Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_TASK"."TASK_ID" IS 'TaskId trên BPM.';
   COMMENT ON COLUMN "DTL_BPM_INST_TASK"."DATA" IS 'Data của Task';
   COMMENT ON COLUMN "DTL_BPM_INST_TASK"."CREATE_DATE" IS 'Ngày tạo trên database. Default = SYSDATE';
