--DROP TABLE ADM_DATATYPE;

CREATE TABLE ADM_DATATYPE
  (
    CODE_TYPE VARCHAR2(50),
    STATE_TYPE VARCHAR(30),
    DATE_TYPE DATE,
    CONTENT_TYPE VARCHAR2(500),
    NAME_TYPE VARCHAR2(100),
    DATA_TYPE CLOB
  );
