--DROP TABLE "DTL_BPM_INST_BO";

CREATE TABLE "DTL_BPM_INST_BO" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "INST_BO_CODE" VARCHAR2(50) DEFAULT ('INS2' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "INST_MASTER_CODE" VARCHAR2(50),
   "DATA" CLOB,
   "CREATE_DATE" DATE DEFAULT SYSDATE,
   CONSTRAINT "DTL_BPM_INST_BO_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "DTL_BPM_INST_BO_CTR_1" UNIQUE (INST_MASTER_CODE)
   );
   COMMENT ON COLUMN "DTL_BPM_INST_BO"."INST_MASTER_CODE" IS 'Mã quản lý Instance trên database (UNIQUE) ref với INSTANCE_MASTER_CODE trong bảng BPM_INSTANCE_MASTER.';
   COMMENT ON COLUMN "DTL_BPM_INST_BO"."DATA" IS 'Data của Instance';
   COMMENT ON COLUMN "DTL_BPM_INST_BO"."CREATE_DATE" IS 'Ngày tạo trên database. Default = SYSDATE';
