--DROP TABLE "BPM_ROOT_INSTANCE";

CREATE TABLE "BPM_ROOT_INSTANCE" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "ROOT_INSTANCE_CODE" VARCHAR2(50) DEFAULT ('INS0' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "INSTANCE_ID" VARCHAR2(50),
	 "PULL_TIME" DATE DEFAULT SYSDATE,
   "DATA" CLOB,
   CONSTRAINT "BPM_ROOT_INSTANCE_PK" PRIMARY KEY ("ID")
   );
   COMMENT ON COLUMN "BPM_ROOT_INSTANCE"."ROOT_INSTANCE_CODE" IS 'Mã quản lý Instance trên database';
   COMMENT ON COLUMN "BPM_ROOT_INSTANCE"."INSTANCE_ID" IS 'Mã instance ứng với InstanceID trên BPM';
   COMMENT ON COLUMN "BPM_ROOT_INSTANCE"."PULL_TIME" IS 'Thời gian kéo instance về database';
   COMMENT ON COLUMN "BPM_ROOT_INSTANCE"."DATA" IS 'Tất cả data lấy từ instance trên BPM';
