--DROP TABLE "BPM_DIAGRAM_MASTER";

CREATE TABLE "BPM_DIAGRAM_MASTER" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "DIAGRAM_MASTER_CODE" VARCHAR2(50) DEFAULT ('DIA1' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "STEP_INFO" CLOB,
   "LANE_INFO" CLOB,
	 "CREATE_DATE" DATE DEFAULT SYSDATE,
   CONSTRAINT "BPM_DIAGRAM_MASTER_PK" PRIMARY KEY ("ID")
   );
   COMMENT ON COLUMN "BPM_DIAGRAM_MASTER"."DIAGRAM_MASTER_CODE" IS 'Mã quản lý Diagram theo Instance trên database';
   COMMENT ON COLUMN "BPM_DIAGRAM_MASTER"."STEP_INFO" IS 'Info data của Step theo Instance';
   COMMENT ON COLUMN "BPM_DIAGRAM_MASTER"."LANE_INFO" IS 'Info data của Lane theo Instance';
   COMMENT ON COLUMN "BPM_DIAGRAM_MASTER"."CREATE_DATE" IS 'Ngày tạo trên database. Default = SYSDATE';
