--DROP TABLE "DTL_BPM_INST_TREE";

CREATE TABLE "DTL_BPM_INST_TREE" 
   (	
   "ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
   "INST_TREE_CODE" VARCHAR2(50) DEFAULT ('INS3' || to_char(SYSDATE, 'yymmdd') || to_char("BPM_INSTANCE_SEQ"."NEXTVAL")),
   "INST_MASTER_CODE" VARCHAR2(50),
   "ROOT_INFO" CLOB,
   "CHILDREN_INFO" CLOB,
	 "CREATE_DATE" DATE DEFAULT SYSDATE,
   CONSTRAINT "DTL_BPM_INST_TREE_PK" PRIMARY KEY ("ID")
   );
   COMMENT ON COLUMN "DTL_BPM_INST_TREE"."INST_TREE_CODE" IS 'Mã quản lý Execution-tree theo Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_TREE"."INST_MASTER_CODE" IS 'Mã quản lý Instance trên database';
   COMMENT ON COLUMN "DTL_BPM_INST_TREE"."ROOT_INFO" IS 'Info data của root';
   COMMENT ON COLUMN "DTL_BPM_INST_TREE"."CHILDREN_INFO" IS 'Info data của children';
   COMMENT ON COLUMN "DTL_BPM_INST_TREE"."CREATE_DATE" IS 'Ngày tạo trên database. Default = SYSDATE';
