-- use for 'ADM_SEQUENCE_MASTER'
CREATE SEQUENCE "ADM_SEQUENCE_SEQ"
       START WITH 1
       INCREMENT BY 1
       NOMAXVALUE
       NOCYCLE
       CACHE 20;

-- use for 'BPM_INSTANCE_MASTER'
CREATE SEQUENCE "BPM_INSTANCES_SEQ" 
       START WITH 1
       INCREMENT BY 1
       NOMAXVALUE
       NOCYCLE
       CACHE 20;
       
