INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('ADM', 'Quản trị', 'SEQ', '1', 'ADM_SEQUENCE', 'ADM_SEQUENCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '0', 'BPM_ROOT_INSTANCE', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '1', 'DTL_BPM_INST_MASTER', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '2', 'DTL_BPM_INST_BO', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '3', 'DTL_BPM_INST_TREE', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '4', 'DTL_BPM_INST_DIAGRAM', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '5', 'DTL_BPM_INST_TASK', 'BPM_INSTANCE_SEQ');

COMMIT;
