INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('ADM', 'Quản trị', 'SEQ', '1', 'ADM_SEQUENCE_MASTER', 'ADM_SEQUENCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '0', 'BPM_ROOT_INSTANCE', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '1', 'BPM_INSTANCE_MASTER', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'INS', '2', 'BPM_INSTANCE_BUSINESS_OBJECT', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'EXE', '1', 'BPM_EXECUTION_TREE', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'DIA', '1', 'BPM_DIAGRAM_MASTER', 'BPM_INSTANCE_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'TSK', '1', 'BPM_TASK_MASTER', 'BPM_TASK_SEQ');
INSERT INTO ADM_SEQUENCE_MASTER(MODULE_SIGN, MODULE_NAME, "CODE", SUB_CODE, TABLE_NAME, SEG_NAME) VALUES('BPM', 'BPM', 'TSK', '2', 'BPM_TASK_DETAIL', 'BPM_TASK_SEQ');
COMMIT;
